### ISSUE TITLE
Segnalazione errore validazione

### ISSUE THREAD

**Issue by ricboc** [WPGov/amministrazione-trasparente#1]
Nel file shortcodes-sezioni.php alla riga 98
manca il tag alt, andrebbe inserito nel prossimo aggiornamento

E sempre nello stesso file alla riga 23 mi segnala
<style type="text/css">
Contexts in which element style may be used:
    If the scoped attribute is absent: where metadata content is expected.
    If the scoped attribute is absent: in a noscript element that is a child of a head element.
    If the scoped attribute is present: where flow content is expected, but before any other flow content other than inter-element whitespace and style elements, and not as the child of an element whose content model is transparent.
Content model for element div:Flow content. 
grazie di tutto
riccardo

**Comment by milesimarco** [comment]
Grazie Riccardo. Appena possibile correggo!

**Comment by ricboc** [comment]
Perfetto, grazie a te!
Ho notato che utilizzando il "nuovo shortcode" ([at-sezioni col="2" bar="2" con="1"]) ci sono altri problemi di validazione:
Nel file shortcodes-sezioni
errore: "Element div not allowed as child of element h3 in this context. (Suppressing further errors from this subtree.)". sostituendo alla riga 83 div con span l'errore si risolve
...e visto che ci siamo, sempre utilizzando il "nuovo shortcode":
nel file shortcodes-search.php, utilizzando il "nuovo shortcode" ([at-sezioni col="2" bar="2" con="1"]) compare l'errore "Duplicate ID searchform". Alla riga 1, cambiando il nome all' id="searchform" con id="searchformat" (ma ovviamente può essere quello che vuoi) l'errore viene eliminato.
...e ancora:
Compare "The name attribute on the option element is obsolete. Use the id attribute instead",
alla riga 16 cambiando "name" con "id" l'errore si risolve
riccardo

**Comment by ricboc** [comment]
Ciao marco, purtroppo nella fretta forse ti sei confuso
alla riga 98 del file shortcodes-sezioni.php dovevi aggiungere il tag alt 
così
            <a href="http://www.wpgov.it" target="_blank" alt="Software WPGov" title="Software WPGov"><img alt="Software WPGov" src="' . plugin_dir_url(__FILE__) . 'wpgov.png" /></a>

e non così
            <a href="http://www.wpgov.it" target="_blank" alt="Software WPGov" title="Software WPGov"><img src="' . plugin_dir_url(__FILE__) . 'wpgov.png" /></a>
;)
