### ISSUE TITLE
Integrazione con tema "Design Comuni Italia" e ricerca

### ISSUE THREAD

**Issue by mariantanase** [WPGov/amministrazione-trasparente#4]
Ciao Marco,
Questa nuova versione è possibile integrarla nel tema "Design Comuni Italia" (WordPress) ?
O almeno risolvere il problema della ricerca che non funziona.
Grazie

**Comment by milesimarco** [comment]
Ciao @mariantanase 
di seguito le PR di compabilità del plugin:

Modello Scuole:
- https://github.com/italia/design-scuole-wordpress-theme/pull/423
- https://github.com/italia/design-scuole-wordpress-theme/pull/424

Modello Comuni:
- https://github.com/italia/design-comuni-wordpress-theme/pull/337

Grazie per la tua segnalazione e se ci sono problemi resto a disposizione
![Screenshot 2023-08-02 175224](https://github.com/WPGov/amministrazione-trasparente/assets/3340185/898d9799-26fc-443e-93e5-1a195aa48fcc)

**Comment by mariantanase** [comment]
Grazie, funziona !
