### ISSUE TITLE
Il template di questa pagina non è ancora disponibile

### ISSUE THREAD

**Issue by mariantanase** [WPGov/amministrazione-trasparente#5]
Ciao Marco,
Nel dettaglio del contenuto inserito in Amministrazione Trasparente, esce questo avviso "_Il template di questa pagina non è ancora disponibile_." 

![Screenshot 2023-08-03 at 09-11-39 Atti amministrativi generali – Nome del Comune](https://github.com/WPGov/amministrazione-trasparente/assets/3976174/9dc424e1-a7a4-42a0-bf62-a5e6fc568dca)

**Comment by mariantanase** [comment]
Risolto

**Comment by milesimarco** [comment]
Ciao @mariantanase,
hai aggiunto il template nel child o hai risolto in altro modo?

**Comment by mariantanase** [comment]
si, ho aggiunto un semplice template nel child
